# Generated by Django 5.1.4 on 2024-12-23 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
    ]
