# Generated by Django 4.2.20 on 2025-03-22 01:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_classification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classification',
            name='document',
        ),
        migrations.RemoveField(
            model_name='classification',
            name='email',
        ),
        migrations.RemoveField(
            model_name='classification',
            name='name',
        ),
        migrations.RemoveField(
            model_name='classification',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='classification',
            name='registrationDate',
        ),
        migrations.AddField(
            model_name='classification',
            name='date_created',
            field=models.DateField(default=datetime.date(2025, 3, 22), verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='classification',
            name='date_updated',
            field=models.DateField(default=datetime.date(2025, 3, 22), verbose_name='Date Updated'),
        ),
        migrations.AddField(
            model_name='classification',
            name='party',
            field=models.CharField(default='Liberal', max_length=128, verbose_name='Party'),
        ),
        migrations.AddField(
            model_name='classification',
            name='text',
            field=models.CharField(default='No Information Provided', max_length=2048, verbose_name='Text'),
        ),
    ]
