# Generated by Django 4.2.20 on 2025-04-06 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0003_remove_classification_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='model_version',
            field=models.CharField(default='pre-release', max_length=128, verbose_name='Model Version'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classification',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2025, 4, 6, 17, 29, 31, 695414, tzinfo=datetime.timezone.utc), verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2025, 4, 6, 17, 29, 31, 695434, tzinfo=datetime.timezone.utc), verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='text',
            field=models.CharField(max_length=4096, verbose_name='Text'),
        ),
    ]
