version: "3.8"
services:
  front-end:
    build: front-end
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/app
    depends_on:
      - back-end
    networks:
      - frontend-backend
  back-end:
    build: backend
    ports:
      - "8000:8000"
    volumes:
      - "./backend:/app"
    networks:
      - frontend-backend

networks:
  frontend-backend:
    driver: bridge
